import React from 'react';
import Head from 'next/head';

import rocketseatLogo from '../assets/rocketseat.svg';
import { Container } from '../styles/pages/Home';

const Home: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <img src={rocketseatLogo} alt="" />
      <h1>ReactJS Structure</h1>
      <p>A ReactJS + Next.js structure made by Rocketseat</p>

    </Container>
  )
}

export default Home;
